# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.vm.define "central-mqtt" do |server|
    server.vm.box = "bento/ubuntu-14.04"
    # virtual backend
	server.vm.network "private_network", ip: "192.168.70.11"
    server.vm.provider "virtualbox" do |virtualbox|
      virtualbox.memory = 2048
      virtualbox.cpus = 2
      virtualbox.gui = true
    end
    server.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible_local/central-mqtt.yml"
    end        
  end
  (1..2).each do |i|
    config.vm.define "local-mqtt-#{i}" do |server|
      server.vm.box = "bento/ubuntu-14.04"
      # virtual backend
	  server.vm.network "private_network", ip: "192.168.70.#{11+i}"
      server.vm.provider "virtualbox" do |virtualbox|
        virtualbox.memory = 2048
        virtualbox.cpus = 2
        virtualbox.gui = true
      end
      server.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "ansible_local/local-mqtt-#{i}.yml"
      end
    end
  end
end