# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure("2") do |config|
  config.vm.define "1-tier-mqtt" do |server|
    server.vm.box = "bento/ubuntu-14.04"
    # virtual backend
	server.vm.network "private_network", ip: "192.168.80.11"
    server.vm.provider "virtualbox" do |virtualbox|
      virtualbox.memory = 1024
      virtualbox.cpus = 1
      virtualbox.gui = true
    end
    server.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible_local/1-tier-mqtt.yml"
    end        
  end
  (1..2).each do |i|
    config.vm.define "2-tier-mqtt-#{i}" do |server|
      server.vm.box = "bento/ubuntu-14.04"
      # virtual backend
	  server.vm.network "private_network", ip: "192.168.80.#{20+i}"
      server.vm.provider "virtualbox" do |virtualbox|
        virtualbox.memory = 1024
        virtualbox.cpus = 1
        virtualbox.gui = true
      end
      server.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "ansible_local/2-tier-mqtt-#{i}.yml"
      end
    end
  end
  (1..4).each do |i|
    config.vm.define "3-tier-mqtt-#{i}" do |server|
      server.vm.box = "bento/ubuntu-14.04"
      # virtual backend
	  server.vm.network "private_network", ip: "192.168.80.#{30+i}"
      server.vm.provider "virtualbox" do |virtualbox|
        virtualbox.memory = 1024
        virtualbox.cpus = 1
        virtualbox.gui = true
      end
      server.vm.provision "ansible_local" do |ansible|
        ansible.playbook = "ansible_local/3-tier-mqtt-#{i}.yml"
      end
    end
  end
end